# Use of the latest Ubuntu image from Docker
FROM ubuntu:latest

# Update APT packages
RUN apt-get update

# Upgrade currently installed packages with APT
RUN apt-get upgrade -y

# Run the command
CMD echo "Hello World"
